export const MOOD_TAGS = [
  { key: "peaceful", label: { vi: "Yên bình", en: "Peaceful" } },
  { key: "adventure", label: { vi: "Phiêu lưu", en: "Adventure" } },
  { key: "culture", label: { vi: "Văn hóa", en: "Culture" } },
  { key: "history", label: { vi: "Lịch sử", en: "History" } },
  { key: "nature", label: { vi: "Thiên nhiên", en: "Nature" } },
  { key: "cuisine", label: { vi: "Ẩm thực", en: "Cuisine" } },
  { key: "spiritual", label: { vi: "Tâm linh", en: "Spiritual" } },
  { key: "romantic", label: { vi: "Lãng mạn", en: "Romantic" } },
  { key: "family", label: { vi: "Gia đình", en: "Family" } },
  { key: "luxury", label: { vi: "Sang trọng", en: "Luxury" } },
  { key: "budget", label: { vi: "Tiết kiệm", en: "Budget" } },
  { key: "beach", label: { vi: "Biển đảo", en: "Beach" } },
  { key: "mountain", label: { vi: "Núi rừng", en: "Mountain" } },
  { key: "city", label: { vi: "Thành phố", en: "City" } },
  { key: "nightlife", label: { vi: "Sôi động", en: "Nightlife" } },
  { key: "shopping", label: { vi: "Mua sắm", en: "Shopping" } },
];
